### ISSUE TITLE
docker/docker-compose.publish.yml doesn't exist

### ISSUE THREAD

**Issue by PaulST2** [poyaz/docker-forticlient#13]
The readme instructions for running with a published port include:

`
docker-compose \
  -f docker-compose.yml \
  -f docker/docker-compose.env.yml \
  -f docker/docker-compose.publish.yml \
  up -d`
  
  But the file docker/docker-compose.publish.yml appears not to exist

**Comment by poyaz** [comment]
Thank you for found this problem.

I change the compose structure and publish port is enabled by default. I have forgotten change this part.

I will fix it.

**Comment by WingCH** [comment]
how to fix?
