### ISSUE TITLE
Use it for RDP

### ISSUE THREAD

**Issue by salvatoregiardina88** [poyaz/docker-forticlient#2]
Hi,
I would like to use it for an RDP connection over VPN.

I would like to run a docker container with docker-forticlient connected to a vpn and then use the RDP of my windows to connect to a remote desktop inside the VPN where the docker container is connected to.

i would like to do that because I would like to run more then 1 container (eachone connected to a different VPN) and connect to multiple RDP located in different VPNs.
Can you help me to understand how to modify what you already did in order to achieve my target?

Thanks in advance

**Comment by poyaz** [comment]
You can use `socat` to forward RDP over a VPN connection 

Like the socks container (I made on docker-compos) you can create a `socat` container over the VPN network and connect to your RDP server 

Please see this article:
https://superuser.com/a/1533178

**Comment by salvatoregiardina88** [comment]
Sounds good but I can't do it. Should I use this rancher/socat-docker?
How should I use it? I'm not able to use docker compose. What should I change in your code?

**Comment by salvatoregiardina88** [comment]
What instead something like that https://hub.docker.com/r/jakubv/docker-forticlient? Does it make sense to you?

**Comment by poyaz** [comment]
> What instead something like that https://hub.docker.com/r/jakubv/docker-forticlient? Does it make sense to you?

Yes you can use it, I think it is better for your purposes

**Comment by poyaz** [comment]
> Sounds good but I can't do it. Should I use this rancher/socat-docker? How should I use it? I'm not able to use docker compose. What should I change in your code?

You can use `rancher/docker` or `alpine/docker`

Just need run another container over VPN container and forward RDP port on socat

**Comment by salvatoregiardina88** [comment]
> > What instead something like that https://hub.docker.com/r/jakubv/docker-forticlient? Does it make sense to you?
> 
> Yes you can use it, I think it is better for your purposes
I can't because it isn't forticlient 7.
I was wondering about the solution adopted

**Comment by salvatoregiardina88** [comment]
> > Sounds good but I can't do it. Should I use this rancher/socat-docker? How should I use it? I'm not able to use docker compose. What should I change in your code?
> 
> You can use `rancher/docker` or `alpine/docker`
> 
> Just need run another container over VPN container and forward RDP port on socat

Ok I will try but to be honest I really don't know how to do that 😭

**Comment by poyaz** [comment]
> > > Sounds good but I can't do it. Should I use this rancher/socat-docker? How should I use it? I'm not able to use docker compose. What should I change in your code?
> > 
> > 
> > You can use `rancher/docker` or `alpine/docker`
> > Just need run another container over VPN container and forward RDP port on socat
> 
> Ok I will try but to be honest I really don't know how to do that 😭

I happend sample for using port forwarder on existence VPN container 

https://github.com/poyaz/docker-forticlient/blob/master/README.md#run-forti-client-container-with-port-forwarder

**Comment by salvatoregiardina88** [comment]
Great! I'll try as soon as possible, will it work with windows and wsl2 too?

**Comment by salvatoregiardina88** [comment]
P.s.: thanks 🙏

**Comment by poyaz** [comment]
> Great! I'll try as soon as possible, will it work with windows and wsl2 too?

Yeah, it's work with wsl2

**Comment by salvatoregiardina88** [comment]
Hi, I've tried it out but I've got this error and can0t find out the solution.
When I try to create the second container:


docker: Error response from daemon: conflicting options: port publishing and the container type network mode.

**Comment by poyaz** [comment]
> Hi, I've tried it out but I've got this error and can0t find out the solution. When I try to create the second container:
> 
> ### RDP port forwarder
> docker run -it --name your-forwarder-container-name --network container:your-vpn-container-name -p 3389:3389 alpine/socat:latest tcp4-listen:3389,reuseaddr tcp:your-rdp-destination-addr:3389
> 
> docker: Error response from daemon: conflicting options: port publishing and the container type network mode.

Sorry, I made a mistake and I forgot to put port mapping on the parent container

I fix it, please try it and get feedback to me


```bash
docker run -it \
  --name your-vpn-container-name \
  --device /dev/net/tun:/dev/net/tun \
  --device /dev/ppp:/dev/ppp \
  --cap-add NET_ADMIN \
  -p 3389:3389 \
  -e VPN_ADDR=host:port \
  -e VPN_USER=me@domain \
  -e VPN_PASS=secret \
  poyaz/forticlient:latest

### RDP port forwarder
docker run -it \
  --name your-forwarder-container-name \
  --network container:your-vpn-container-name \
  alpine/socat:latest tcp4-listen:3389,reuseaddr tcp:your-rdp-destination-addr:3389
```

**Comment by salvatoregiardina88** [comment]
I cannot ping the containers from windows as well...

**Comment by poyaz** [comment]
> Tring to compose multiple vpn:
> 
> https://github.com/poyaz/docker-forticlient#with-multi-vpn-instance I get this error: time="2023-03-20T15:30:18+01:00" level=warning msg="The "PWD" variable is not set. Defaulting to a blank string." time="2023-03-20T15:30:18+01:00" level=warning msg="The "PWD" variable is not set. Defaulting to a blank string." open C:\Users\salva\Downloads\forti\docker-forticlient-master\env\vpn\ .env: The system cannot find the file specified.

I fixed `$PWD` for windows

**Comment by poyaz** [comment]
> should I call the first vpn just .env?

If you use one instance of vpn, You should copy `env/vpn/.env.example` to `env/vpn/.env` and run compose

---

If you want create multi instance of vpn, You should following bellow steps:

1. Copy `env/vpn/.env.example` to `env/vpn/vpn-1.env` (Or any name you want)
2. Fill your vpn identity on `env/vpn/vpn-1.env`
3. Copy `env/vpn/.env.example` to `env/vpn/vpn-2.env` (Or any name you want)
4. Fill your vpn identity on `env/vpn/vpn-2.env`
5. Execute bellow command for run **forticlient** and **socks5**

```bash
COMPOSE_PROJECT_NAME=vpn-1 FORTI_VPN_ENV=env/vpn/vpn-1.env docker-compose \
  -f docker-compose.yml \
  -f docker/docker-compose.env.yml \
  up -d

COMPOSE_PROJECT_NAME=vpn-2 FORTI_VPN_ENV=env/vpn/vpn-2.env docker-compose \
  -f docker-compose.yml \
  -f docker/docker-compose.env.yml \
  up -d
```

With port forwarder and publish port on host:

```bash
### Run VPN-1 and forwarder RDP port to remote-server-1
### socks5 server: 127.0.0.1:1080
### socat server: 127.0.0.1:3389
COMPOSE_PROJECT_NAME=vpn-1 FORTI_VPN_ENV=env/vpn/vpn-1.env FORTI_SOCKS_PORT=8080 FORTI_SOCAT_PORT=3389 FORTI_SOCAT_DEST_ADDR=remote-server-1 FORTI_SOCAT_DEST_PORT=3389 docker-compose \
  -f docker-compose.yml \
  -f docker/docker-compose.env.yml \
  -f docker/docker-compose.publish.yml \
  -f docker/docker-compose.socat.yml \
  -f docker/docker-compose.socat-publish.yml \
  up -d
  
### Run VPN-2 and forwarder RDP port to remote-server-2
### socks5 server: 127.0.0.1:1081
### socat server: 127.0.0.1:3390
COMPOSE_PROJECT_NAME=vpn-2 FORTI_VPN_ENV=env/vpn/vpn-2.env FORTI_SOCKS_PORT=1081 FORTI_SOCAT_PORT=3390 FORTI_SOCAT_DEST_ADDR=remote-server-2 FORTI_SOCAT_DEST_PORT=3389 docker-compose \
  -f docker-compose.yml \
  -f docker/docker-compose.env.yml \
  -f docker/docker-compose.publish.yml \
  -f docker/docker-compose.socat.yml \
  -f docker/docker-compose.socat-publish.yml \
  up -d
```

**Comment by salvatoregiardina88** [comment]
When I try to compose:
docker-compose -f docker-compose.yml -f docker/docker-compose.env.yml -f docker/docker-compose.publish.yml -f docker/docker-compose.socat.yml -f docker/docker-compose.socat-publish.yml up -d

I get this error:
yaml: line 6: did not find expected ',' or ']'

I've tried to figure out which file and which problem is, but I don't understand where is the problem

**Comment by salvatoregiardina88** [comment]
I don't know if its correct...
But I've tried to create only vpn-1.env and vpn-2.env but I had received the errore about missing env/vpn/.env file, so I've created a .env file with inside the variables I should declare before the docker-compose command and since that I've got the error of the previous post.

**Comment by salvatoregiardina88** [comment]
Hi,
They were correctly compiled and running, but I cannot reach rdp.
I tried to pind dest addr and works, but in socat container I have this log:
2023/03/21 14:28:14 socat[1] E empty port/service

and seems no port open.
Did I make any mistake?

**Comment by salvatoregiardina88** [comment]
I tried in different ways on declaring variables but I think the problem is that the variables are kept inside the vpn container and are not passed to socat container. Is that possible? Inspecting the vpn container I see all variables fulfilled, but if I inspect the socat container I don't see any variable. Maybe we should create and .env file for socat?

**Comment by poyaz** [comment]
> I tried in different ways on declaring variables but I think the problem is that the variables are kept inside the vpn container and are not passed to socat container. Is that possible? Inspecting the vpn container I see all variables fulfilled, but if I inspect the socat container I don't see any variable. Maybe we should create and .env file for socat?

You don't use `FORTI_SOCAT_DEST_ADDR` and `FORTI_SOCAT_DEST_PORT` inside the env file. This environment should use before docker-compose command like below:

```bash
FORTI_SOCAT_DEST_ADDR=remote-addr FORTI_SOCAT_DEST_PORT=3389 FORTI_SOCAT_PORT=3389 docker-compose -f ... up -d

**Comment by salvatoregiardina88** [comment]
Yes, I confirm that the problem is the variables in windows.
I've tried change those into the file and it works!
Thank you so much!

Any suggestion on what to change to use also an openvpn container?

**Comment by poyaz** [comment]
> Yes, I confirm that the problem is the variables in windows. I've tried to change those into the file and it works! Thank you so much!
> 
> Any suggestion on what to change to use also an OpenVPN container?

Well done

For a change in the OpenVPN container for the environment, you should change the **docker-compose.publish.yml** variable.

Also because you can't use env, to run multi-instance compose files you have to follow below steps:

1. Create a custom compose file and modified with your configuration 
2. Use `docker-compose --project <name> -f ... up -d` to create a multi-instance of the VPN service with the prefix namespace
