### ISSUE TITLE
Iptables issues when starting container

### ISSUE THREAD

**Issue by goooroooX** [poyaz/docker-forticlient#7]
Hi,

I'm trying to get this image working on Synology NAS with following errors:
>> 2023/11/08 02:48:27,stderr,Try `iptables -h' or 'iptables --help' for more information.
>> 2023/11/08 02:48:27,stderr,iptables v1.8.2 (nf_tables): Chain 'MASQUERADE' does not exist

Container is always restarting.
Can you please suggest how to fix it?

**Comment by goooroooX** [comment]
This can probably be fixed by adding following to startup script:
> update-alternatives --set iptables /usr/sbin/iptables-legacy

There also issue with getting 2FA token from file - looks like expect script is terminating after user has wrote file.

**Comment by poyaz** [comment]
Thank you for finding this problem

Please send me your kernel and operation system to find and solve **iptables** problem

**Comment by goooroooX** [comment]
Hi!

My system is Synology DS220+ with DSM 7.2-64570 Update 1 running. 

```
sh-4.4# uname -a
Linux NAS 4.4.302+ #64570 SMP Tue Jun 13 21:39:55 CST 2023 x86_64 GNU/Linux synology_geminilake_220+
sh-4.4# iptables
iptables v1.8.3 (legacy): no command specified
Try `iptables -h' or 'iptables --help' for more information.
```

I have tested suggestion above with 'update-alternatives' - it works fine when added to startup script before iptables manipulation.

However, it does not work properly with 2FA in my setup - expect script is exiting after writing 2fa file.

I'm thinking of different approach for 2FA - it might be more convenient to change workflow to the following sequence:
- VPN is not starting with container
- 'inotifywait' is looking for any writes (close_write,moved_to,create) for 2FA files
- when new 2FA token is available in file, any existent VPN instance is terminated and new one connect 
- no automatic restart for VPN service

Is 2FA currently works when running this image on other systems?

**Comment by poyaz** [comment]
I have tested 2FA on one of my colleagues and it working. But it may have a problem in another system.
I create more tests for 2FA and I will tell you as soon as possible

Thank you

**Comment by goooroooX** [comment]
Just FYI, 'inotifywait' implementation in 2FA script may require change. It may not capture file write when modified with editor that may not just write file, but replace it ([here](https://superuser.com/a/181543) are some details). 

Probably, something like that:

```
inotifywait -e close_write,moved_to,create -m "${VPN_2FA_DIR}" |
while read -r directory events filename; do
  echo "`date` -- $filename" > ${VPN_2FA_DIR}/folder.log
  if [ "$filename" = "${VPN_2FA_FILE}" ]; then
    cat "${VPN_2FA_FILE}" | tr -d "\n"
    exit 0
  fi
done
```

**Comment by poyaz** [comment]
Hi again

Thank you for your time in solving the problem, Could you please test this feature and if all thins is okay create PR to solve this bug?

**P.S:**
 I am thinking about this problem. In my opinion, we can use `nc` command to get the 2fa code and write it.
But Unfortunately, I am busy and I can't be able to implement this feature now

**Comment by goooroooX** [comment]
If I will manage to fix it for my scenario with Synology NAS, I will definitely post either solution description or PR.

**Comment by poyaz** [comment]
You can update image to new version. if it's okay and it's work then use in real image

**Comment by goooroooX** [comment]
It seems openfortivpn v.1.21.0 works fine for my 2FA scenario (I don't really know why it works for you, this probably depends on VPN server version also. I've tested it in a separate alpine image.
As for this debian image: is there any simple way to build it with v.1.21.0? I don't think it can be installed with apt-get.

**Comment by goooroooX** [comment]
I've ended up with building my own Alpine-based image for 2FA-only: https://github.com/goooroooX/docker-forti-proxy-2fa/
Thank you for your assistance.

**Comment by poyaz** [comment]
Fantastic, well done

Thank you for spend time for fix problem
