### ISSUE TITLE
Update to use newer base image like bookworm (12.x)

### ISSUE THREAD

**Issue by asrob** [poyaz/docker-forticlient#9]
Hi!

As I can see, this docker image uses debian buster. However buster will be supported until 30th June, 2024. Can you update to use newer base image like bookworm (12.x)?

**Comment by poyaz** [comment]
Hi

It was updated to `debian:bookworm` and be able in docker image version 2.0.0 (and latest)

```bash
# Or docker pull poyaz/forticlient:lastet
docker pull poyaz/forticlient:2.0.0
```
